### ISSUE TITLE
add a reason field to fill out when creating a join request

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ucb-rit/coldfront#128]
based on discussion, a user being able to join a whole bunch of projects by just clicking the join button is a valid concern. Add a `reason` popup modal form which is to be submitted along with the `ProjectJoinRequest`.

**Comment by matthew-li** [comment]
@ViRu-ThE-ViRuS There's a subtlety to consider here:
- Users are able to join projects that are still pending to be created.
- Auto-approvals for join requests occur via a cron job that looks at the latest-created `ProjectUserJoinRequest` for each pending `ProjectUser` on each "Active" `Project`.
- The auto-approval delay should not start ticking until the project actually becomes "Active", so the PI actually has an opportunity to approve/deny these requests.
- This logic is implemented in the [Project.save](https://github.com/ucb-rit/coldfront/blob/develop/coldfront/core/project/models.py#L76) method. When a `Project`'s status changes from something to "Active", it recreates `ProjectUserJoinRequests` for pending users so that the delay will begin at the same time as the project is approved.

All of that background is to say that the `reason` field, which I assume will be added to `ProjectUserJoinRequest`, must be propagated from the previously-existing, latest-created request to the newly-created duplicate in this method, so that it isn't lost. Essentially, in the `save` method, for each pending `ProjectUser`, you'll want to find its latest-created join request, and copy over its `reason` when creating the new one.

Let me know if any of this is unclear.
