### ISSUE TITLE
Write convenient database queries

### ISSUE THREAD

**Issue by matthew-li** [ucb-rit/coldfront#167]
We should be able to make the following queries easily:

- Generate a list of primary email addresses.
    - Filter: include only PIs.
    - Filter: include only users with cluster accounts.
    - Filter: include only users who have ever authenticated to the portal.

Write a management command that prints out the results, and/or a front-end view for admins.

It may be useful to generate graphs from these queries.

**Comment by matthew-li** [comment]
Below is a query that returns all users who have ever logged in:

```
from django.contrib.auth.models import User
User.objects.filter(last_login__isnull=False)
```

**Comment by matthew-li** [comment]
@kmuriki We should create a list of common queries you'd expect to come up here.

**Comment by matthew-li** [comment]
@Leon-Goldner-Cohen-Tzedek Can you spend some time brainstorming a list of metrics/tools you think might be useful to admins/users, based on the data we store in the database?

This is pretty open-ended, so there aren't really right or wrong answers (although some may be more/less implementable).

Some examples might be:
- How many jobs were submitted (under this project) (by this user) (since this date) (before this date)?
- How many users logged in (since this date)?
- How many requests (of this type) were made? How do the numbers break down by allocation type?
- What percentage of users have submitted a job (since this date) (before this date)?

The answers to questions like these might best be represented by graphs/charts in the UI, downloadable CSV files, etc.

**Comment by matthew-li** [comment]
On a related note, BRC has a [Grafana](https://grafana.brc.berkeley.edu/) instance.

**Comment by Leon-Goldner-Cohen-Tzedek** [comment]
Honestly I think you already found most of the interesting uses for this data, and that really this seems like it would be the most useful as a dashboard like grafana but in the portal so that some performance questions can be answered by the system. 

It would be the most useful for there to be a view in the portal for seeing this information and/or relevant numbers being presented in the projects tabs, though that might be a bit distracting. How we present this information could be an interesting visualization project because, for example, we could show partitions and nodes graphically and then color them in as they are being used with the data collected from core/statistics/model.py

All of this being live updating and the such with some pretty animations would make it that much cooler, but I'm not sure how useful that would be. 

The information that can be extracted with:
- data from core/statistics:
  - number of jobs being run
  - number of nodes being used 
 - data from core/project
   - number of projects
   - number of users 

This is data we store that I think is interesting, and that most importantly can be turned into information that is interesting as well for example:
- taking the number of jobs being run per user
- number of jobs being run per project
  - which projects are running the most jobs

**Comment by wfeinstein** [comment]
I think we focus on getting some basic information done, then work on visualization.

- Project list (+ active list), including fc_, ac_, co_. ic_, with PI name, email address
- User list (+ active user list), who have submitted given a staring date
- New user account list given a staring date
- New project list given a staring date
- More job related coming up

**Comment by matthew-li** [comment]
I've created branch `issue_167`, with a management command `export_data` under `core.utils`.

This takes one of multiple sub-commands, which we'll define. Each of these sub-commands can have its own arguments.

Below are some sample commands:

```
python manage.py export_data sample_a --allowance_type ac_
python manage.py export_data sample_b csv                    # format is required.
```

We'll want to name the sub-commands appropriately (i.e., `projects`, `users`, etc.).

@ViRu-ThE-ViRuS Can you work on the project-related queries described above?
@jofeinstein Can you work on the user-related queries described above and the query for average job queue time?

You should be able to work on the same branch.

I'm leaving this fairly open-ended, so use your best judgment, but let me know if you have any questions.
