### ISSUE TITLE
Keep Survey Responses visible after FCA project has been approved and activated

### ISSUE THREAD

**Issue by markyashar** [ucb-rit/coldfront#394]
When an administrator is processing and setting up an  FCA project on the MyBRC Portal, the survey responses in the FCA application are visible and accessible (via the "Survey Responses" button) to the administrator (and perhaps other consultants) within the MyBRC portal. However, after the FCA project is approved and set up on the BRC cluster and is active, it doesn't appear as if those survey responses are visible/accessible anymore within the portal (?) It might be useful to keep those survey responses visible/accessible for everyone (maybe by including the FCA "Survey Responses" button on the project page) even after the FCA project has been set up and is active. This would enable administrators, consultants, and others to have a better idea and more information about the research project and the computational needs of active FCA/PCA (and other) projects on the cluster.

**Comment by matthew-li** [comment]
@markyashar Thanks for the suggestion.

The survey responses _should_ still be visible:
- For Superusers and Staff (let me know if you're not able to see them):
    - `/project/savio-project-completed-request-list/` (Admin > Requests > New Savio Project Requests > (completed link in the help text)).
    - `/user/request-hub-admin` (Admin > Requests > All Requests)
- Additionally, the requesters/PIs of the individual requests may view their requests from the Requests page listed in the nav-bar.

However, as you noted, it may be useful to include these responses directly in the Project's main page. We can address that in an upcoming release.

(There may be multiple sets of responses due to pooling.)
