### ISSUE TITLE
get_compute_resource_names causing errors when generating new database

### ISSUE THREAD

**Issue by jofeinstein** [ucb-rit/coldfront#395]

**Comment by matthew-li** [comment]
For context, commands like `migrate`, `makemigrations`, etc. were failing with this error:

```
psycopg2.errors.UndefinedTable: relation \"resource_resource\" does not exist
```

This is because `ProjectSearchForm.CLUSTER_NAME_CHOICES` is calculated as Django is being initialized. This calls `get_compute_resource_names`, which filters `Resources` from the database. However, the `Resource` table does not exist yet.

[Reference](https://stackoverflow.com/a/68590729)

Computing the choices for the field can be done in `__init__` instead, which is only invoked when the class is initialized.
